version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  api:
    build:
      context: ./server  # indicate path
      dockerfile: Dockerfile.dev  
    volumes:
      - /app/node_modules  # don't map reference to node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      context: ./client  
      dockerfile: Dockerfile.dev  
    volumes:
      - /app/node_modules  
      - ./client:/app
  worker:
    build:
      context: ./worker  
      dockerfile: Dockerfile.dev  
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules  
      - ./worker:/app





      
